services:
  - type: web
    name: telegram-media-bot
    runtime: python

    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt

    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: WHISPER_MODEL
        value: tiny