services:
  - type: web
    name: khmer-srt-voice-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
